<?php

namespace app\models;

use Yii;
use common\models\Products;
use common\models\ProductsCategories;
use yii\web\UploadedFile;

/**
 * This is the model class for table "categories".
 *
 * @property int $id
 * @property string $title
 * @property string $body
 * @property int $image_id
 * @property int $parent_id
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property int $deleted_at
 * @property int $seo
 *
 * @property Categories $parent
 * @property Categories[] $categories
 * @property ProductsCategories[] $productsCategories
 * @property Products[] $products
 */
class Categories extends \yii\db\ActiveRecord
{
    public $image;
    public $galery = [];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'categories';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'body'], 'required'],
            [['body'], 'string'],
            [['image_id', 'parent_id', 'status', 'created_at', 'updated_at', 'deleted_at', 'seo'], 'integer'],
            [['title'], 'string', 'max' => 225],
            [['parent_id'], 'exist', 'skipOnError' => true, 'targetClass' => Categories::className(), 'targetAttribute' => ['parent_id' => 'id']],
            [['image'], 'file', 'extensions' => 'png, jpg'],
            [['galery'], 'file', 'extensions' => 'png, jpg', 'maxFiles' => 4]

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'body' => 'Body',
            'image' => 'Головне зораження',
            'galery' => 'Галерея',
            'parent_id' => 'Parent ID',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'seo' => 'Seo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne(Categories::className(), ['id' => 'parent_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Categories::className(), ['parent_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductsCategories()
    {
        return $this->hasMany(ProductsCategories::className(), ['categories_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasMany(Products::className(), ['id' => 'products_id'])->viaTable('products_categories', ['categories_id' => 'id']);
    }

    public function getAllCategoriesAsArray()
    {
        $categories = Categories::find()->all();
        $dropdownData = \yii\helpers\ArrayHelper::map($categories, 'id', 'title');
        return $dropdownData;
    }

    public function delete()
    {
        $this->deleted_at = time();
        $this->status = 2;
        $this->save(false); // TODO: Change the autogenerated stub
//        dd($this);
        return true;
    }

    public function upload()
    {
        if ($this->validate()) {
            $path = 'uploads/store/' . $this->image->baseName . '.' . $this->image->extension;
            $this->image->saveAs($path);
            $this->attachImage($path);
            @unlink($path);
            return true;
        } else return false;
    }

    public function uploadGalery()
    {
        if ($this->validate()) {
            foreach ($this->galery as $file) {
                $path = 'uploads/store/' . $file->baseName . '.' . $file->extension;
                $file->saveAs($path);
                $this->attachImage($path);
                @unlink($path);
            }
            return true;
        } else return false;
    }
}
